openapi: 3.0.0
info:
  title: Customer API
  version: 1.0.0
  description: API documentation for Customer Management
paths:
  /customers:
    get:
      summary: Get all customers
      tags:
        - Customers
      responses:
        200:
          description: A list of customers
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Customer'
    post:
      summary: Create a new customer
      tags:
        - Customers
      requestBody:
        description: Customer object that needs to be added to the system
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        201:
          description: Customer created successfully
        400:
          description: Invalid input
  /customers/{id}:
    get:
      summary: Get a customer by ID
      tags:
        - Customers
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        200:
          description: Customer details
        404:
          description: Customer not found
    put:
      summary: Update a customer by ID
      tags:
        - Customers
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        description: Customer object with updated details
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Customer'
      responses:
        200:
          description: Customer updated successfully
        400:
          description: Invalid input
        404:
          description: Customer not found
    delete:
      summary: Delete a customer by ID
      tags:
        - Customers
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
     
